language: go
sudo: false

go_import_path: github.com/klaper_/mqtt_data_exporter

services:
- docker

go:
- 1.13.x

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src

install:
  - go get

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...