language: go

go_import_path: github.com/klaper_/mqtt_data_exporter

services:
- docker

go:
- 1.12.x

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure